# Generated by Django 3.0.2 on 2022-05-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0003_aboutsection_banner_news'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
