# Generated by Django 3.0.2 on 2022-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0006_footer_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='about_text',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='links',
            new_name='quick_links',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='designation',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='long_desc',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='message',
            new_name='short_message',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='long_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_links',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='long_message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
