# Generated by Django 3.0.2 on 2022-05-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0007_auto_20220510_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
