# Generated by Django 3.0.2 on 2022-05-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0008_auto_20220510_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='content',
        ),
    ]
