# Generated by Django 3.0.2 on 2022-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0009_remove_footer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='quick_links',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social_links',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='sub_menu_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
