# Generated by Django 3.0.2 on 2022-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0011_auto_20220510_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='quick_links',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
