# Generated by Django 3.0.2 on 2022-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0013_news_news_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
