# Generated by Django 3.0.2 on 2022-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0014_news_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='long_desc',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
