# Generated by Django 3.0.2 on 2022-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0015_auto_20220510_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
