# Generated by Django 3.0.2 on 2022-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0016_message_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='static/blogs')),
                ('blog_title', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=500, null=True)),
                ('short_decs', models.TextField(blank=True, max_length=1000, null=True)),
                ('long_desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
