# Generated by Django 3.0.2 on 2022-05-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0017_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_decs',
            new_name='short_desc',
        ),
    ]
