# Generated by Django 3.0.2 on 2022-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0019_gallery_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
