# Generated by Django 3.0.2 on 2022-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0020_banner_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_first', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('logo_second', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logo',
            },
        ),
    ]
