# Generated by Django 3.0.2 on 2022-05-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0022_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='tagline',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
