# Generated by Django 3.0.2 on 2022-05-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0023_logo_tagline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logo',
            new_name='SiteIdentity',
        ),
    ]
