# Generated by Django 3.0.2 on 2022-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0024_auto_20220517_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='social_links',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
