# Generated by Django 3.0.2 on 2022-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0025_auto_20220517_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=500, null=True)),
                ('current_address', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_no', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('gpa', models.CharField(blank=True, max_length=500, null=True)),
                ('school_name', models.CharField(blank=True, max_length=500, null=True)),
                ('school_address', models.CharField(blank=True, max_length=500, null=True)),
                ('stream', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admissionform',
            },
        ),
    ]
