# Generated by Django 3.0.2 on 2022-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0026_admissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='sub_menu_link',
        ),
        migrations.AddField(
            model_name='submenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='long_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='short_content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
