# Generated by Django 3.0.2 on 2022-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0027_auto_20220518_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
