# Generated by Django 3.0.2 on 2022-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0029_submenu_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_index',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
