# Generated by Django 3.0.2 on 2022-05-19 19:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0030_menu_menu_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_link',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
