# Generated by Django 3.0.2 on 2022-05-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0032_auto_20220519_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='menu',
            name='long_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='short_content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
