# Generated by Django 3.0.2 on 2022-06-10 06:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0033_auto_20220520_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='long_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='short_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='long_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='short_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='long_message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='short_message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
    ]
