# Generated by Django 3.0.2 on 2022-05-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0033_auto_20220520_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
    ]
