# Generated by Django 3.0.2 on 2022-06-03 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0033_auto_20220520_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
    ]
