# Generated by Django 3.0.2 on 2022-06-14 06:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0034_auto_20220610_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_position',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='heading',
        ),
        migrations.AlterField(
            model_name='blog',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='long_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='short_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='long_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='short_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='long_message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='short_message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
