# Generated by Django 3.0.2 on 2022-06-03 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0034_auto_20220603_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='long_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
