# Generated by Django 3.0.2 on 2022-05-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0034_footer_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='license_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
