# Generated by Django 3.0.2 on 2022-06-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0035_auto_20220614_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='quick_links',
        ),
    ]
