# Generated by Django 3.0.2 on 2022-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0036_auto_20220527_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
