# Generated by Django 3.0.2 on 2022-06-16 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0036_remove_footer_quick_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
