# Generated by Django 3.0.2 on 2022-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0037_auto_20220527_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
