# Generated by Django 3.0.2 on 2022-06-30 04:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0037_footer_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
