# Generated by Django 3.0.2 on 2022-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0038_auto_20220527_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
