# Generated by Django 3.0.2 on 2022-05-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0039_auto_20220527_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_desc',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
