# Generated by Django 3.0.2 on 2022-05-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0040_auto_20220527_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_desc',
        ),
    ]
