# Generated by Django 3.0.2 on 2022-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0045_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
