# Generated by Django 3.0.2 on 2022-06-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0050_auto_20220613_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionprocess',
            name='short_desc',
        ),
    ]
