# Generated by Django 3.0.2 on 2022-06-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0051_remove_selectionprocess_short_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selectionprocess',
            table='selectionprocess',
        ),
    ]
