# Generated by Django 3.0.2 on 2022-06-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0052_auto_20220613_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_position',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='quick_links',
        ),
    ]
