# Generated by Django 3.0.2 on 2022-06-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasaapp', '0053_auto_20220614_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='heading',
        ),
    ]
